release, and readme update to make the warning a little less scary
apostrophecms/apostrophe-media-sources pull request #12
Opened 2021-01-28 19:57 UTC by boutell

2021-01-28 20:35 UTC, boutell commented
This became a more ambitious update of the README, so I've assigned to both Val and Bea for review. Let me know if I missed anything.

2021-01-28 22:29 UTC, abea requested changes

2021-01-28 22:29 UTC, abea commented on README.md
> +        accessKey: process.env.UNSPLASH_ACCESS_KEY
hella indented

2021-01-28 22:29 UTC, abea commented on README.md
> +* `async find (req, filters)`:
Are these _not_ placed on the `self` object?

2021-01-28 22:29 UTC, abea commented on README.md
> +```
Did you mean to remove the syntax indicator from ```js?

2021-02-01 14:02 UTC, boutell commented on README.md
> +**When using this module, your site cannot be edited in the IE11 browser.** Modern Microsoft Edge browsers work just fine. This site does not affect the experience of ordinary logged-out site visitor
Clarified

2021-02-01 14:02 UTC, boutell commented on README.md
> +      'apostrophe-media-sources-wedia': {
It's not an OR, you may use one or the other or both or write more etc. So I don't think there's any appropriate language there, it's just a couple o' modules hangin' out.

2021-02-01 14:03 UTC, boutell commented on README.md
> +* `async find (req, filters)`:
The `async` keyword made me crazy? I think I've fixed this, by showing that expectation while still using the actual valid syntax.

2021-02-01 15:40 UTC, abea approved these changes

2021-02-01 16:40 UTC, ValJed approved these changes
Thanks for the improvements!

2021-02-03 16:38 UTC, merged