pass options from module config to wedia content picker
apostrophecms/apostrophe-media-sources pull request #15
Opened 2021-02-23 16:50 UTC by ValJed

2021-02-23 17:29 UTC, falkodev requested changes

2021-02-23 17:29 UTC, falkodev commented on README.md
> +          options: {} // optional - pass options to the wedia content picker -}
Why a final `}` on this line?

```
wedia content picker -}
```

2021-02-23 17:29 UTC, falkodev commented on README.md
> +* to access the `Unsplash` API you will need to create a free developer account, which will provide you with an access key, this free account is limited to 50 requests per hour. For Wedia you will ne
If you start the previous paragraph with an uppercase letter, I think this one needs it too.

2021-03-01 12:03 UTC, ValJed commented on README.md
> +          options: {} // optional - pass options to the wedia content picker -}
Removed

2021-03-01 12:03 UTC, ValJed commented on README.md
> +* to access the `Unsplash` API you will need to create a free developer account, which will provide you with an access key, this free account is limited to 50 requests per hour. For Wedia you will ne
Yup, fixed

2021-03-01 16:05 UTC, falkodev approved these changes

2021-03-02 17:22 UTC, merged