98 get unsplash credit infos
apostrophecms/apostrophe-media-sources pull request #17
Opened 2021-03-10 10:04 UTC by ValJed

* Get credit infos from unsplash and store it in DB.
* Modify  `find` and `download` Unsplash responses to show to the user if the error is a `Rate Limit Exceeded`. Otherwise just notify with the standard error.

2021-03-12 08:58 UTC, falkodev requested changes

2021-03-12 08:58 UTC, falkodev commented on lib/modules/apostrophe-media-sources-unsplash/index.js
> +            credit: {
I end up with a credit field containing [Oject object]:

![image](https://user-images.githubusercontent.com/11479686/110916787-7547e880-8319-11eb-9181-36470a2db634.png)

2021-03-16 14:51 UTC, ValJed commented on lib/modules/apostrophe-media-sources-unsplash/index.js
> +            credit: {
Yes, new fields have been added in new tab.

2021-05-10 07:03 UTC, falkodev approved these changes

2021-05-19 08:15 UTC, merged