38 disable imported images
apostrophecms/apostrophe-media-sources pull request #5
Opened 2020-12-10 10:35 UTC by ValJed

2020-12-10 13:58 UTC, ValJed commented on lib/modules/apostrophe-media-sources-unsplash/index.js
> +      const existingImages = await self.apos.images.find(req, {
Yes you right !

2020-12-10 14:31 UTC, stuartromanek approved these changes

2020-12-10 14:31 UTC, stuartromanek commented on README.md
> +Notice that the `Unsplash` Api require to create a free developper account which will provide you an access key.
typo `developper`

2020-12-10 15:13 UTC, ValJed commented on README.md
> +Notice that the `Unsplash` Api require to create a free developper account which will provide you an access key.
Oh yes, thanks

2020-12-10 19:39 UTC, boutell requested changes

2020-12-10 19:39 UTC, boutell commented on README.md
> +Of course you should use an environment variable, to avoid storing key in your source code.
storing keys (not key)

2020-12-10 19:39 UTC, boutell commented on README.md
> +Of course you should use an environment variable, to avoid storing key in your source code.
"Alternatively you may use an environment variable" would be better. A private repo is not a terrible place for keys on a smaller project. At enterprise scale you need to keep those in environment specific locations yes.

2020-12-10 19:39 UTC, boutell commented on README.md
> +What we call a connector is a module which connect the `apostrophe-media-sources` to a specific provider.
"which connects the apostrophe image library to a specific provider"

2020-12-10 19:39 UTC, boutell commented on README.md
> +## Create you own connector
your own

2020-12-10 19:39 UTC, boutell commented on README.md
> +Each module must have a `mediaSourceConnector` config in options :
must have a `mediaSourceConnector` option:

2020-12-10 19:39 UTC, boutell commented on README.md
> +      standardFilters: [ // Should work for every provider
Need to list the possible values here and acknowledge that some of them might not be specified for every provider if they simply cannot be implemented for it.

2020-12-10 19:39 UTC, boutell commented on README.md
> +      standardFilters: [ // Should work for every provider
Or maybe these are all of the possible ones?

2020-12-10 19:39 UTC, boutell commented on README.md
> +          choices: [
Choices are hardcoded? These should come back from the `choices` method of the connector as I described here:

https://www.notion.so/apostrophetechnologies/Technical-Design-a5613ffcf74e40689c1497e90c7a6c35#cfaf7c8bd7a4445a9554c8c2945fb72c

This way it is possible to support truly dynamic choices which is important for things like tags or categories.

2020-12-10 19:39 UTC, boutell commented on README.md
> +
`choices` is currently missing.

2020-12-10 19:39 UTC, boutell commented on README.md
> +And the `mediaSource` property, which is the name of the module, for Unsplash (`apostrophe-media-sources-unsplash`).
Why do they have to store it? Doesn't the main module do this for them at import time?

2020-12-10 19:39 UTC, boutell commented on README.md
> +Finally it has to return the ids of the created images pieces.
The creation of the attachment and the pieces should be handled in the main module, removing duplicate code from the connectors. This method should only be responsible for fetching the file. Also it is not documented what the method expects from `files`, is that equivalent to `Images` in the previous example?

2020-12-14 12:22 UTC, ValJed commented on README.md
> +Finally it has to return the ids of the created images pieces.
Ok indeed we could avoid duplicate code, but in this case we don't need any download method in the connector module because, the find method must already format data adding a `downloadLink`, the url we use to download the image.
So if we move the download logic into the main component, I don't think we need to keep it in the connector.

2020-12-14 12:23 UTC, ValJed commented on README.md
> +And the `mediaSource` property, which is the name of the module, for Unsplash (`apostrophe-media-sources-unsplash`).
Yes it could, see my next comment.

2020-12-14 12:32 UTC, ValJed commented on README.md
> +      standardFilters: [ // Should work for every provider
This is the part we had difficulty understanding.
If by `standardFilters` you mean filters that exist for every provider, how could we know the future providers which will be implemented will support these filters ?

2020-12-14 12:42 UTC, ValJed commented on README.md
> +          choices: [
Yes choices are hardcoded, I think you wanted us to ask to the Unsplash Api the filters and their values ? But Unsplash doesn't provide any dynamic informations about this. I'ts only documented.
This is why I didn't get the point of making something like this dynamic. I assume we could add this method for the next Dams which will provide dynamic informations about filters and values.

About tags and categories, in you example here:
https://www.notion.so/Technical-Design-a5613ffcf74e40689c1497e90c7a6c35#9d3ce886f7b740aca0cb1b26fc551505

You call the choices method passing two categories, and you get back 5. So it means that you add two possible categories to the ones already existing in the connector ?

2020-12-14 12:42 UTC, ValJed commented on README.md
> +
Yes, see my previous comments

2020-12-14 13:42 UTC, boutell requested changes

2020-12-14 13:42 UTC, boutell commented on README.md
> +      standardFilters: [ // Should work for every provider
I think this is correct in the current version of the code. For each one that the backend does support, you have `name` and if necessary, `dependsOn`. That does make sense.

But this comment is about the documentation. The *documentation in the README for creating new connectors* should mention *all* of the standardFilters that you *might* support, so you know what the possibilities are when you are writing a new connector and you do not implement as "custom" things that should be "standard."

2020-12-14 13:42 UTC, boutell commented on README.md
> +          choices: [
As you say, tags and categories exist and they are dynamic. And there may be other such custom fields. It would not make sense to hardcode the choices for them. In addition, the choices for each filter must take the *current values of other filters into account.* In most cases a filter should not offer choices that lead to zero results. So even filters that seem to be static may be dynamic. This is why the choices function should always be used.

But if it needs to return static results every time for a particular filter, it can do that. For instance, maybe a backend can't tell us what categories actually exist for a specific orientation, or when other filters are in effect in general. If not that's OK, it can return all of them. But only if that's the best it can do.

Re: passing two categories and getting back 5, in my example the user is already filtering on two categories. But the choices for "categories" that come back should not be filtered by category, otherwise you can't change your mind and pick another one.

So the choices for filter X must take into account the current value of filter Y, but not it is own current value.

For clarification here is what the algorithm looks like in Apostrophe 3.x pieces pages, which is a pretty readable example powered by Apostrophe's own queries. For your project it must be powered by the backend the connector is designed to talk to instead.

https://github.com/apostrophecms/apostrophe/blob/f003a9c29ee1cef5769e655516335d20e3c3fec3/modules/%40apostrophecms/piece-page-type/index.js#L349

Again, if the backend cannot give you the possible choices for a filter based on other filters, then it is OK to return all the choices.

2020-12-14 13:42 UTC, boutell commented on README.md
> +Finally it has to return the ids of the created images pieces.
Yes move as much logic out of the connector as you possibly can, without ever writing connector-specific logic in the main module. If it is used by all connectors it belongs in the main module.

2020-12-15 09:45 UTC, ValJed commented on README.md
> +      standardFilters: [ // Should work for every provider
Ok, There are all the possible ones for now yes

2020-12-15 09:46 UTC, ValJed commented on README.md
> +          choices: [
Thanks for these precisions, I added the choices method, and made the filters dynamics.

2020-12-15 09:46 UTC, ValJed commented on README.md
> +Finally it has to return the ids of the created images pieces.
Done, we only keep a simple download method on connector side

2020-12-15 09:51 UTC, ValJed commented on README.md
> +
Added

2020-12-15 09:51 UTC, ValJed commented on README.md
> +And the `mediaSource` property, which is the name of the module, for Unsplash (`apostrophe-media-sources-unsplash`).
Done

2020-12-16 13:29 UTC, boutell requested changes

2020-12-16 13:29 UTC, boutell commented on lib/modules/apostrophe-media-sources-unsplash/index.js
>            data.pipe(writer);
Can you use `pipeline` to simplify this code? If you promisify `pipeline` it should become possible to just `await` the whole mess (:

https://nodejs.org/docs/latest-v10.x/api/stream.html#stream_stream_pipeline_streams_callback

2020-12-16 13:29 UTC, boutell commented on lib/modules/apostrophe-media-sources-unsplash/index.js
>            data.pipe(writer);
(It requires node 10 but this is a new module and node 8 is obsolete anyway so we can document the requirement.)

2020-12-16 13:31 UTC, boutell approved these changes
`pipeline` is really just a suggestion so I'm going to approve.

2020-12-16 15:10 UTC, ValJed commented on README.md
> +      standardFilters: [ // There are all the standard filters for now
Ok just added the list of standard filters after.

2020-12-16 17:04 UTC, ValJed commented on lib/modules/apostrophe-media-sources-unsplash/index.js
>            data.pipe(writer);
Really good idea, just did it and it's way more readable :+1:

2020-12-16 17:10 UTC, merged